on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to run github action
    steps:
    - name: Run Action Step
      id: hello
      uses: actions/pylint3-action@v2
      with:
        filename: 'test.py'
