on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to run github action
    steps:
    - name: Run Action Step
      id: hello
      uses: actions/PyLint-Action@v1
      with:
        filename: 'test.py'
